# Generated by Django 4.1.2 on 2022-12-02 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0008_remove_message_public_message_message_response_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=4096)),
            ],
        ),
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 2, 18, 2, 34, 851269)
            ),
        ),
    ]
