# Generated by Django 4.1.3 on 2022-12-02 18:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_user_profile_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_response',
        ),
        migrations.RemoveField(
            model_name='message',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 18, 23, 11, 363511)),
        ),
        migrations.DeleteModel(
            name='MessageResponse',
        ),
    ]
