# Generated by Django 4.1.2 on 2022-12-05 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_alter_message_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 5, 14, 44, 40, 189351)
            ),
        ),
    ]
