# Generated by Django 4.1.2 on 2022-12-05 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_alter_message_message_response_alter_message_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 5, 17, 55, 25, 446199)
            ),
        ),
    ]
