# Generated by Django 4.1.3 on 2022-12-07 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_remove_user_profile_profile_user_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 15, 1, 1, 302017)),
        ),
    ]
