# Generated by Django 4.1.2 on 2022-12-09 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_remove_profile_user_user_profile_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='picture.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 9, 55, 50, 435233)),
        ),
    ]
