# Generated by Django 4.1.2 on 2022-12-09 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_message_time_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 10, 22, 54, 662259)),
        ),
    ]
