# Generated by Django 4.1.3 on 2022-12-10 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_alter_message_time_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 21, 41, 47, 734281)),
        ),
    ]
