# Generated by Django 4.1.4 on 2022-12-11 00:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 0, 26, 30, 330908)),
        ),
    ]
