# Generated by Django 4.1.4 on 2022-12-11 01:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_profile_user_acc_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_on', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 1, 7, 16, 799552)),
        ),
    ]
