# Generated by Django 4.1.4 on 2022-12-11 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_product_highest_bidder_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 1, 11, 9, 549224)),
        ),
    ]
