# Generated by Django 4.1.4 on 2022-12-15 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_alter_message_time_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 15, 11, 48, 507513)),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='./media/images/images.png', upload_to='images'),
        ),
    ]
