# Generated by Django 4.1.4 on 2022-12-15 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_alter_message_time_alter_product_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 15, 16, 40, 390516)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../images/images.png', upload_to='images'),
        ),
    ]
