# Generated by Django 4.1.4 on 2022-12-15 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0053_alter_message_time_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 19, 42, 38, 326905)),
        ),
    ]
