# Generated by Django 4.1.4 on 2022-12-16 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0061_alter_message_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_response",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response",
                to="authentication.messageresponse",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 16, 14, 40, 30, 878317)
            ),
        ),
    ]
